export const STATIC_PROJECTS = [
  {
    _id: 'emrast',
    projectName: 'EMRAST',
    fullTitle: "Early Multi-Modal Alzheimer's Risk Assessment & Sensing Technology",
    status: 'Clinical Phase II',
    phase: 'Phase II',
    nihGrant: 'R44AG082621',
    fundingAmount: 2947375,
    description: "Multimodal diagnostic platform combining psychophysical olfactory assessment with ML-based biomarker classification for pre-clinical Alzheimer's detection.",
    marketStatus: 'Clinical Validation',
    photos: ['https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=700&q=80'],
    role: 'Principal Investigator',
    agency: 'NIH / NIA',
    nihAwards: [
      { type: 'Phase I', year: 2023, amount: 448887, id: '1R44AG082621-01' },
      { type: 'Phase II', year: 2024, amount: 1249244, id: '4R44AG082621-02' },
      { type: 'Phase II', year: 2025, amount: 1249244, id: '5R44AG082621-03' },
    ],
    engineeringChallenges: [
      'Designing calibrated, reproducible olfactory stimulus delivery across diverse clinical environments',
      'Integrating multi-modal physiological sensing within a standardized clinical workflow',
      'Developing ML classification models robust to real-world measurement variability',
      'Building FDA Design History File architecture alongside rapid iterative development',
      'Ensuring patient compliance across populations with varying cognitive status',
    ],
    technologyDomains: ['Bioelectronics', 'Machine Learning', 'FDA 21 CFR 820', 'ISO 13485', 'Signal Processing', 'HIPAA Architecture'],
    publicationDoi: 'Article ID: TRC270226, Alzheimer\'s & Dementia: Translational Research & Clinical Interventions',
    currentStatus: 'Clinical Phase II — Active. Multi-site validation ongoing under NIH SBIR Phase II through 2025.',
  },
  {
    _id: 'editor',
    projectName: 'EDITOR',
    fullTitle: 'Early Detection & Intervention Tool for Opioid Recovery',
    status: 'Phase II Active',
    phase: 'Phase II',
    nihGrant: 'R44DA056156',
    fundingAmount: 2704509,
    description: 'Connected RPM ecosystem featuring a novel non-infrared pupillometer enabling objective neurological assessment for opioid use disorder monitoring and clinical trials.',
    marketStatus: 'Active Development',
    photos: ['https://images.unsplash.com/photo-1559757175-5700dde675bc?w=700&q=80'],
    role: 'Co-Investigator',
    agency: 'NIH / NIDA',
    nihAwards: [
      { type: 'Phase I', year: 2022, amount: 330680, id: '1R44DA056156-01' },
      { type: 'I-CORPS', year: 2023, amount: 55000, id: '3R44DA056156-01S1' },
      { type: 'Phase II', year: 2023, amount: 1318829, id: '4R44DA056156-02' },
      { type: 'Phase II', year: 2023, amount: 1000000, id: '5R44DA056156-03' },
    ],
    engineeringChallenges: [
      'Achieving sub-millimeter spatial resolution at 250Hz sampling rate in a portable form factor',
      'Custom near-infrared optoelectronic array design for accurate pupillary tracking across diverse iris pigmentation',
      'Edge AI deployment for real-time Neurological Performance Index (NPI) computation',
      'HIPAA-compliant cloud telemetry architecture for multi-site RPM deployment',
      'Ensuring BLE connectivity reliability in clinical environments with RF interference',
    ],
    technologyDomains: ['Optoelectronics', 'Edge AI', 'BLE 5.0', 'AWS IoT', 'IEC 60601', 'HIPAA Architecture'],
    publicationDoi: 'USPTO Patent Application No. 63/774,619 — Pupillometer and Related Methods',
    currentStatus: 'Phase II Active — Multi-site clinical deployment under NIH/NIDA funding.',
  },
  {
    _id: 'cbotp',
    projectName: 'CBOT-P',
    fullTitle: 'Chronic Pain Neurosensory Therapeutic Platform',
    status: 'Pre-FDA Submission',
    phase: 'Phase II',
    nihGrant: 'R44AG061981',
    fundingAmount: 2791180,
    description: 'FDA Breakthrough Device designated electromechanical neurostimulation platform for chronic pain management. ISO 13485 QMS compliant with real-time neural feedback.',
    marketStatus: 'Pre-FDA Submission',
    photos: ['https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=700&q=80'],
    role: 'Co-Investigator',
    agency: 'NIH / NIA & NINDS',
    nihAwards: [
      { type: 'Phase I', year: 2018, amount: 225000, id: '1R43AG061981-01' },
      { type: 'Phase I', year: 2019, amount: 225000, id: '5R43AG061981-02' },
      { type: 'Phase II', year: 2021, amount: 1247784, id: '2R44AG061981-03A1' },
      { type: 'Supplement', year: 2022, amount: 98280, id: '3R44AG061981-04S2' },
      { type: 'TABA', year: 2022, amount: 50000, id: '3R44AG061981-04S1' },
      { type: 'Phase II', year: 2022, amount: 1245116, id: '5R44AG061981-04' },
    ],
    engineeringChallenges: [
      'Achieving electromechanical precision actuation within FDA-compliant device architecture',
      'Real-time neural feedback integration with hardware control loop latency requirements',
      'Battery and power management for therapeutic device usage patterns',
      'IEC 60601 electrical safety compliance across all hardware revisions',
      'Building ISO 13485 QMS documentation infrastructure alongside active R&D',
    ],
    technologyDomains: ['Electromechanical Engineering', 'Neurostimulation', 'ISO 13485', 'IEC 60601', 'FDA 21 CFR 820', 'Real-Time Control'],
    publicationDoi: 'USPTO Application No. 18/753,722 — Pain Treatment Apparatus and Methods',
    currentStatus: 'FDA Breakthrough Device Designation received. Pre-FDA submission activities ongoing.',
  },
  {
    _id: 'memorydriver',
    projectName: 'MemoryDriver',
    fullTitle: 'AI-Powered Digital Therapeutic for Cognitive Longevity',
    status: 'Market Ready',
    phase: 'DTx',
    nihGrant: 'Internal R&D (Non-NIH)',
    fundingAmount: null,
    description: 'Patented iOS digital therapeutic combining AI-driven cognitive assessments with personalized brain training. HIPAA-compliant and built 0-to-1 as a commercial product.',
    marketStatus: 'Market Ready',
    photos: ['https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=700&q=80'],
    role: 'Product Lead & Inventor',
    agency: 'Internal R&D',
    nihAwards: [],
    engineeringChallenges: [
      'Designing AI classification algorithms that generalize across diverse user populations',
      'Achieving HIPAA compliance in a consumer-facing mobile application architecture',
      'Building adaptive difficulty systems that maintain optimal cognitive challenge zones',
      'Creating a 0-to-1 development pipeline from user research through App Store deployment',
      'Structuring longitudinal performance data for potential clinical research applications',
    ],
    technologyDomains: ['iOS Development', 'Machine Learning', 'AWS Architecture', 'HIPAA Compliance', 'UX Design', 'Digital Therapeutics'],
    publicationDoi: 'USPTO Patent Application No. 63/783,072 — Memory Impairment Classifier Apparatus',
    currentStatus: 'Market Ready — Available on iOS. Commercial launch phase.',
  },
  {
    _id: 'cannula',
    projectName: 'Smart Nasal Cannula',
    fullTitle: 'Connected Respiratory Monitoring Platform',
    status: 'Active Development',
    phase: 'R&D',
    nihGrant: 'Internal R&D',
    fundingAmount: null,
    description: 'BLE 5.0 + AWS IoT Core connected wearable with 0.1 L/min micro-flow sensing, SpO₂, PPG sensors, and edge AI for 48+ hour remote respiratory monitoring.',
    marketStatus: 'Active Development',
    photos: ['https://images.unsplash.com/photo-1530026405186-ed1f139313f3?w=700&q=80'],
    role: 'Chief Architect',
    agency: 'Internal R&D',
    nihAwards: [],
    engineeringChallenges: [
      'Miniaturizing multi-modal sensing, BLE radio, and battery into a comfortable 24/7-wear form factor',
      'Achieving clinical-grade SpO₂ accuracy across diverse patient populations and skin tones',
      'Designing micro-flow sensing at 0.1 L/min resolution for clinical respiratory assessment',
      'Ensuring BLE reliability in environments with medical equipment RF interference',
      'Power management for 48+ hour continuous operation meeting IEC 60601 standards',
    ],
    technologyDomains: ['BLE 5.0', 'AWS IoT Core', 'Edge AI', 'Optoelectronics', 'PPG Sensing', 'FHIR Integration'],
    publicationDoi: '',
    currentStatus: 'Active development — hardware validation phase.',
  },
  {
    _id: 'cot',
    projectName: 'COT',
    fullTitle: "Cognitive Optimization Therapy — Disease-Modifying Alzheimer's Intervention",
    status: 'Phase II Active',
    phase: 'Phase II',
    nihGrant: 'R44NS125745',
    fundingAmount: 3129999,
    description: "End-to-end hardware lifecycle for an Alzheimer's disease-modifying intervention device. Full ISO 13485/IEC 62304 compliance with comprehensive usability engineering.",
    marketStatus: 'Active Development',
    photos: ['https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=700&q=80'],
    role: 'Lead Product Engineer',
    agency: 'NIH / NINDS',
    nihAwards: [
      { type: 'Phase I', year: 2022, amount: 499999, id: '1R44NS125745-01A1' },
      { type: 'Phase II', year: 2024, amount: 1349130, id: '4R44NS125745-02' },
      { type: 'Phase II', year: 2025, amount: 1280870, id: '5R44NS125745-03' },
    ],
    engineeringChallenges: [
      'Managing end-to-end hardware lifecycle from concept through manufacturing scale-up',
      'Integrating multi-system validation protocols across hardware and software components',
      'Building IEC 62366 usability engineering files alongside active device development',
      'Coordinating NINDS regulatory strategy with ongoing clinical trial execution',
      'Ensuring ISO 13485 QMS continuity across multiple hardware generation transitions',
    ],
    technologyDomains: ['Hardware Lifecycle Management', 'ISO 13485', 'IEC 62304', 'IEC 62366', 'FDA Design Controls', 'System Validation'],
    publicationDoi: 'USPTO Application No. 19/300,409 — Systems and Methods For Computerized Olfactory Adaptive Training',
    currentStatus: 'Phase II Active — NIH/NINDS funding through 2025.',
  },
];

export default STATIC_PROJECTS;
